= Remove dependency to Spray
kamon-io/kamon-influxdb pull request #2
Opened 2017-01-09 20:14 UTC by pimeys

Spray will not be compatible with Scala 2.13, therefore we should
replace the HTTP client used to send data to InfluxDB with
AsyncHTTPClient.

2017-01-10 09:00 UTC, ivantopo requested changes
I only see that small issue with the log message, otherwise it looks good to me, thanks!

2017-01-10 09:00 UTC, ivantopo commented on src/main/scala/kamon/influxdb/InfluxDBClient.scala
> +          logger.info(s"${response.getStatusCode} ${response.getStatusText}")
wdyt about changing this message to debug level? once all is working, this is just adding noise to the logs. Also something like "Metrics POST to InfluxDB completed with status code X - XTexr" as a message would be a lot easier to identify.

2017-01-10 09:26 UTC, pimeys commented on src/main/scala/kamon/influxdb/InfluxDBClient.scala
> +          logger.info(s"${response.getStatusCode} ${response.getStatusText}")
Actually I just copied the old functionality but you are right. I'll change this when tested properly. :)

2017-01-10 10:24 UTC, pimeys commented
I tested this with real InfluxDB and a test app. I got metrics after fixing a small issue in the URI. Also the success log line is now in DEBUG.

2017-01-12 09:59 UTC, ivantopo approved these changes

2017-01-12 09:59 UTC, merged

2017-01-12 09:59 UTC, ivantopo commented
thanks a lot @pimeys!

2017-01-17 23:34 UTC, pjfanning reviewed
Is it necessary to preserve the compression support in the original code (the Deflate steps)?

2017-01-18 08:24 UTC, pimeys commented
@pjfanning Good catch. It's definitely useful if having lots of metrics and sending them through a slow network. I can consider it missing to be a regression...